// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIBAMSLoginGoogleChromWindow.UIBAMSLoginGoogleChromWindow1.UIChromeLegacyWindowClient;
            WinControl uIChromeLegacyWindowDocument = this.UIBAMSLoginGoogleChromWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Verify that the 'ControlType' property of 'Chrome Legacy Window' client equals 'Client'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIChromeLegacyWindowClientControlType, uIChromeLegacyWindowClient.ControlType.ToString());

            // Verify that the 'AccessibleDescription' property of 'Chrome Legacy Window' document equals ''
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIChromeLegacyWindowDocumentAccessibleDescription, uIChromeLegacyWindowDocument.AccessibleDescription);
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public UIBAMSLoginGoogleChromWindow UIBAMSLoginGoogleChromWindow
        {
            get
            {
                if ((this.mUIBAMSLoginGoogleChromWindow == null))
                {
                    this.mUIBAMSLoginGoogleChromWindow = new UIBAMSLoginGoogleChromWindow();
                }
                return this.mUIBAMSLoginGoogleChromWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private UIBAMSLoginGoogleChromWindow mUIBAMSLoginGoogleChromWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Chrome Legacy Window' client equals 'Client'
        /// </summary>
        public string UIChromeLegacyWindowClientControlType = "Client";
        
        /// <summary>
        /// Verify that the 'AccessibleDescription' property of 'Chrome Legacy Window' document equals ''
        /// </summary>
        public string UIChromeLegacyWindowDocumentAccessibleDescription = null;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBAMSLoginGoogleChromWindow : WinWindow
    {
        
        public UIBAMSLoginGoogleChromWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "BAMS Login - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("BAMS Login - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIBAMSLoginGoogleChromWindow1 UIBAMSLoginGoogleChromWindow1
        {
            get
            {
                if ((this.mUIBAMSLoginGoogleChromWindow1 == null))
                {
                    this.mUIBAMSLoginGoogleChromWindow1 = new UIBAMSLoginGoogleChromWindow1(this);
                }
                return this.mUIBAMSLoginGoogleChromWindow1;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("BAMS Login - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIBAMSLoginGoogleChromWindow1 mUIBAMSLoginGoogleChromWindow1;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIBAMSLoginGoogleChromWindow1 : WinWindow
    {
        
        public UIBAMSLoginGoogleChromWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "BAMS Login";
            this.WindowTitles.Add("BAMS Login - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("BAMS Login - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
}
